apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-devops
  template:
    metadata:
      labels:
        app: web-devops
    spec:
      containers:
        - name: nginx
          image: minha-pagina-nginx:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
