apiVersion: v1
kind: Service
metadata:
  name: web-devops-service
spec:
  type: NodePort
  selector:
    app: web-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
